# Generated by Django 2.2.19 on 2024-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
