# Generated by Django 4.2.1 on 2024-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-time_create'], name='tour_tour_time_cr_340d59_idx'),
        ),
    ]
