# Generated by Django 4.2.18 on 2025-02-07 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tagpost_alter_tour_cat_tour_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'вид спорта', 'verbose_name_plural': 'Виды спорта'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-time_create'], 'verbose_name': 'Турниры', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='tour.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='content',
            field=models.TextField(blank=True, verbose_name='Правила турнира'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(7, message='Минимум 7 символов'), django.core.validators.MaxLengthValidator(100)], verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tour.tagpost', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
